import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Venu application",
  description: "Generated by create next 14 app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    >
    <html lang="en">
      <body className={`${inter.className}  bg-dark-1`}>
        <div className=" min-h-screen w-full flex flex-col justify-center items-center">
            {children}
        </div>
        </body>
    </html>
    </ClerkProvider>
  );
}
